id: PD6731041
initial_creation_type: input
source_metadata:
  title: Third Karmapa Series
  language: bo
  description: 'Texts by and about the Third Karmapa, Rangjung Dorje (karma pa rang
    byung rdo rje, 1284–1339):'
  volume:
    e504cdcb1fc04b42aeaf1b95b889a5d0:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
created_at: '2022-03-01T01:47:35.690667'
last_modified_at: '2022-03-01T01:47:35.690670'
